name = "skill-gap-analysis-api"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "skill-gap-analysis-api"

[env.staging]
name = "skill-gap-analysis-api-staging"

[env.development]
name = "skill-gap-analysis-api-dev"

# Environment variables (set these in Cloudflare dashboard or via wrangler secret) 
[vars]
NODE_ENV = "production"
CORS_ORIGIN = "https://your-frontend-domain.com"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX_REQUESTS = "100"
LOG_LEVEL = "info"

# Secrets (use: wrangler secret put SECRET_NAME)
# JWT_SECRET
# DATABASE_URL (for D1 or external database)
# REDIS_URL (for Upstash Redis or similar)

# D1 Database binding (update with your actual database_id)
[[d1_databases]]
binding = "DB"
database_name = "skill-gap-db"
database_id = "96482268-37bf-4082-bacd-18509c947738"

# KV namespace for caching (update with your actual namespace IDs)
[[kv_namespaces]]
binding = "CACHE"
id = "747058b5407243d9846eb3ca1d6ef563"
preview_id = "1cbf2f6e3d594ddb9214dcc7986c1141"

# Rate limiting using Durable Objects (requires paid plan)
# [[durable_objects.bindings]]
# name = "RATE_LIMITER"
# class_name = "RateLimiter"

# [[migrations]]
# tag = "v1"
# new_classes = ["RateLimiter"]